kind: pipeline
type: docker
name: deployement

volumes:
  - name: repo
    host:
      path: /media/raid5/data/packages/repos/apt/botamusique/

steps:
  - name: build-web
    image: node
    commands:
      - (cd web && npm install && npm run build)
    when:
      event:
        - push

  - name: translate-html
    image: python:3
    commands:
      - pip3 install jinja2
      - ./scripts/translate_templates.py --lang-dir lang/ --template-dir templates/
    when:
      event:
        - push
      instance:
        exclude:
          - drone_runner_outside

  - name: deploy-testing
    image: debian
    commands:
      - apt-get -qq update && apt-get -qq install git > /dev/null
      - sed -i 's/target_version = git/target_version = testing/' configuration.default.ini
      - version=$(git rev-parse HEAD)
      - echo "current git commit is $version"
      - echo $version > /mnt/botamusique/testing-version
      - sed -i "s/version = 'git'/version = '$version'/" mumbleBot.py
      - rm -rf .git*
      - rm -rf web
      - mkdir /tmp/botamusique
      - cp -r . /tmp/botamusique/
      - tar -czf /mnt/botamusique/sources-testing.tar.gz -C /tmp botamusique
    volumes:
      - name: repo
        path: /mnt/botamusique/
    when:
      branch:
        - master
      event:
        - push
      instance:
        exclude:
          - drone_runner_outside
  
  - name: docker-testing
    image: plugins/docker
    settings:
      repo: azlux/botamusique
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: testing
    when:
      branch:
        - master
      event:
        - push
      instance:
        exclude:
          - drone_runner_outside


  - name: deploy-stable
    image: debian
    commands:
      - apt-get -qq update && apt-get -qq install jq curl git pandoc python3-requests > /dev/null
      - sed -i 's/target_version = git/target_version = stable/' configuration.default.ini
      - git fetch --tags
      - version=$(git describe --abbrev=0 --tags)
      - echo "version is $version"
      - echo $version > /mnt/botamusique/version
      - sed -i "s/version = 'git'/version = '$version'/" mumbleBot.py
      - curl --silent "https://api.github.com/repos/azlux/botamusique/releases/latest" | jq -r '.body' | pandoc --from gfm --to html - --output - > /mnt/botamusique/changelog
      - rm -rf .git*
      - rm -rf web
      - mkdir /tmp/botamusique
      - cp -r . /tmp/botamusique/
      - tar -czf /mnt/botamusique/sources-stable.tar.gz -C /tmp botamusique
    volumes:
      - name: repo
        path: /mnt/botamusique/
    when:
      event:
        - tag
      instance:
        exclude:
          - drone_runner_outside

  - name: docker-stable
    image: plugins/docker
    settings:
      repo: azlux/botamusique
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
    when:
      event:
        - tag
      instance:
        exclude:
          - drone_runner_outside

trigger:
  event:
    exclude:
      - cron

---
kind: pipeline
type: docker
name: translation
steps:
  - name: fetch-translation
    image: debian
    environment:
      TRADUORA_R_CLIENT:
        from_secret: TRADUORA_R_CLIENT
      TRADUORA_R_SECRET:
        from_secret: TRADUORA_R_SECRET
      GITHUB_API:
        from_secret: GITHUB_API
    commands:
      - apt update && apt install -y git python3-requests hub
      - SOURCE_DIR=$(pwd) ./scripts/commit_new_translation.sh
    when:
      instance:
          - drone_runner_outside
          
trigger:
  event:
    include:
      - cron
      - push
  cron:
    - auto-fetch-lang
